version: "3"
services:
  mcx80: 
    image: tactis/caddy-cloudflaredns:latest
    restart: unless-stopped
    environment:
      CF_API_TOKEN: 123
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy_data:/data
volumes:
  caddy_data:
    driver: local